### ISSUE TITLE
"unsupported plugin" in phonegap build?

### ISSUE THREAD

**Issue by prantikv** [peteygao/MediaScannerPlugin#1]
it works greate on my cli and does its job.
but i can't seem to add it in phonegap build.

i used
<gap:plugin name="org.sfl.MediaScannerPlugin" />
to add it as that was the folder name in the plugins folder in CLI.
i am using phonegap version 3.6.3
I think the plug-in not registered i was not able to find it on http://plugins.cordova.io
or some problem with the plugin ID is seems
kindly tell me how can i use this in phonegap build

**Comment by siddmegadeth** [comment]
facing the same issue .
Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED from pid=10415, uid=10216

Added 
 <intent-filter>
        <action android:name="android.intent.action.MEDIA_MOUNTED" />
        <data android:scheme="file" />
    </intent-filter>
But still same error. Please suggest
