### ISSUE TITLE
Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED

### ISSUE THREAD

**Issue by prantikv** [peteygao/MediaScannerPlugin#2]
hi,
i was looking for a plugin like this and it does exactly what i was looking for but when i use it i get this
"Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED pid=7474 & uid 97363"
I am getting this on the error callback

i am using it with the phonegop file plugin and was just looking to refresh the the media after creating an image.

i have a refresh button that does the refreshing onClick rather than a success callback of file write

```
    function onDeviceReady() {
     document.getElementById("scan").addEventListener("click",function(){
       alert("Refreshing");
       window.MediaScannerPlugin.scanFile(
                   function(msg){
                              alert("msg "+msg);
                   },
                     function(err){
                          alert("err "+err);
                      }
            );//scanFlie
           }); //onClick

          }//device ready
```

**Comment by Tarabass** [comment]
Did you add permissions to `androidmanifest.xml`?

``` javascript
<intent-filter>
  <action android:name="android.intent.action.MEDIA_MOUNTED" />
  <data android:scheme="file" /> 
</intent-filter>
```

**Comment by prantikv** [comment]
i just added the plugin to the config.xml file like so

  <gap:plugin name="com.verso.cordova.clipboard" version="0.1.0" />

**Comment by siddmegadeth** [comment]
having same issue.added the following line of code but still error coming up

   <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_MOUNTED" />
                <data android:scheme="file" />
            </intent-filter>
        </activity>

Is there anything i am missin here. please guide.

**Comment by lastmjs** [comment]
It looks like this plugin is dated and needs to be rewritten. I've been doing some research, and Android has changed the way it media scans in later versions of Android (I think the change came in 4.4.4, KitKat, see [this answer](http://stackoverflow.com/a/25086535/2196424)). I've forked the repo and made some changes, it seems to work: https://github.com/byuarchdi/MediaScannerPlugin

Maybe with some cleanup on my part we can work together and merge my changes into this repo. If you use the forked plugin, just pass in the full path to the file that you want to be scanned into window.MediaScannerPlugin:

```
window.MediaScannerPlugin.scanFile(fullPathToFile, successCallback, failureCallback)
```

**Comment by vinlim** [comment]
@lastmj  It seems like im getting the similar error using your version. 

Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED from pid=2221, uid=10154

Please advise.

**Comment by vinlim** [comment]
cordova plugin add https://github.com/byuarchdi/MediaScannerPlugin.git

Instead to add the forked version.
