### ISSUE TITLE
Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED from pid=30762, uid=10123 

### ISSUE THREAD

**Issue by siddmegadeth** [peteygao/MediaScannerPlugin#4]
Hi,

On Chrome Inspect this is the message coming up.
Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED from pid=30762, uid=10123 

Any Suggestions,
i am using kitkat 4.4   Redmi 2 with MIUI 7.

**Comment by peteygao** [comment]
Sorry, this is a unmaintained fork of Cavas2ImagePlugin which I used for a single PhoneGap project and then never used it again. You'll have to find other solutions, unfortunately...
